### ISSUE TITLE
Send browser events to Home Assistant

### ISSUE THREAD

**Issue by ScottG489** [bokub/home-assistant-extension#15]
Is this extension able to send browser events (network requests, current page title, etc) to Home Assistant?

It seems like this extension is mostly about controlling HA, but it would be awesome if it could send these kind of events from your browser to HA!

Really great looking extension and thanks for your work on it!

**Comment by bokub** [comment]
Hi,

No, this extension cannot communicate with your home assistant instance, it's nothing more than a pop-up window !

**Comment by ScottG489** [comment]
Is this something you'd be interested in implementing or at very least accepting PRs for?

I ask because it would be a fairly signification architectural change.

**Comment by bokub** [comment]
I don't think it would be a good idea to add these features to this extension, because it's a really different purpose that shares nothing with the original one (and honestly, I'm not sure I understand the use-case).

Why not create a new extension without the mini-viewer and with all the synchronisation features you're talking about? I like the "do one thing and do it well" philosophy

**Comment by ScottG489** [comment]
Use case would be something like an automation triggered when you visit a specific page, submit a specific form, etc.

Totally understand if you don't want to incorporate that into this extension! Can't go wrong with the Unix philosophy :)

Feel free to close if you'd like.

**Comment by bokub** [comment]
Thanks for understanding!
